"""Add thumbnail_key to Photo

Revision ID: 43b91aaa67f7
Revises: 147819250e09
Create Date: 2026-05-18 23:26:09.320029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b91aaa67f7'
down_revision: Union[str, Sequence[str], None] = '147819250e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('thumbnail_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'thumbnail_key')
    # ### end Alembic commands ###
